server:
  port: 9001

spring:
  application:
    name: category-service
  cloud:
    config:
      enabled: true
      url: http://localhost:8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost